// Constantes globales del sistema

export const APP_CONFIG = {
  NOMBRE: 'Sistema de Gestión de Horarios - UNT',
  VERSION: '1.0.0',
  UNIVERSIDAD: 'Universidad Nacional de Trujillo',
  ESCUELA: 'Escuela de Ingeniería de Sistemas',
};

export const HORARIOS = {
  DIAS: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  HORAS_INICIO: 7,
  HORAS_FIN: 22,
};

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMINISTRADOR: 'ADMINISTRADOR',
  OPERADOR: 'OPERADOR',
  DOCENTE: 'DOCENTE',
  MONITOR: 'MONITOR',
};

export const PERMISOS = {
  GESTIONAR_USUARIOS: [ROLES.SUPER_ADMIN],
  GESTIONAR_DOCENTES: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR],
  GESTIONAR_CURSOS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR],
  GESTIONAR_HORARIOS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR, ROLES.OPERADOR],
  PUBLICAR_HORARIOS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR],
  VER_HORARIOS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR, ROLES.OPERADOR, ROLES.DOCENTE],
  GESTIONAR_VENTANAS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR, ROLES.OPERADOR],
  VER_REPORTES: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRADOR],
  CONFIGURAR_SISTEMA: [ROLES.SUPER_ADMIN],
};
